// frontend/src/components/MasonryGrid.jsx
import { useEffect } from 'react';
import { useInView } from 'react-intersection-observer';
import Masonry from 'react-masonry-css';
import ArticleCard from './ArticleCard';
import { useArticles } from '../hooks/useArticles';

const breakpointColumns = {
  default: 4,
  1536: 3,
  1024: 2,
  640: 1
};

export default function MasonryGrid({ onArticleClick, filterUnread, selectedFeed }) {
  const { ref, inView } = useInView();

  const {
    data,
    fetchNextPage,
    hasNextPage,
    isFetchingNextPage,
    status,
  } = useArticles({
    unread: filterUnread,
    feedId: selectedFeed,
  });

  useEffect(() => {
    if (inView && hasNextPage) {
      fetchNextPage();
    }
  }, [inView, hasNextPage, fetchNextPage]);

  if (status === 'pending') {
    return (
      <div className="container mx-auto px-4 py-8">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
          {[...Array(8)].map((_, i) => (
            <div key={i} className="bg-gray-200 animate-pulse rounded-lg h-64"></div>
          ))}
        </div>
      </div>
    );
  }

  if (status === 'error') {
    return (
      <div className="container mx-auto px-4 py-8">
        <div className="text-center text-gray-500">
          <p>Error loading articles. Please try again later.</p>
        </div>
      </div>
    );
  }

  const articles = data?.pages.flatMap(page => page) ?? [];

  if (articles.length === 0) {
    return (
      <div className="container mx-auto px-4 py-8">
        <div className="text-center text-gray-500 py-12">
          <h3 className="text-xl font-semibold mb-2">No articles yet</h3>
          <p>Add some feeds to get started!</p>
        </div>
      </div>
    );
  }

  return (
    <div className="container mx-auto px-4 py-8">
      <Masonry
        breakpointCols={breakpointColumns}
        className="flex -ml-4 w-auto"
        columnClassName="pl-4 bg-clip-padding"
      >
        {articles.map((article) => (
          <ArticleCard
            key={article.id}
            article={article}
            onClick={() => onArticleClick(article)}
          />
        ))}
      </Masonry>

      {hasNextPage && (
        <div ref={ref} className="text-center py-8">
          {isFetchingNextPage ? (
            <div className="text-gray-500">Loading more...</div>
          ) : (
            <div className="text-gray-400">Scroll for more</div>
          )}
        </div>
      )}
    </div>
  );
}

// frontend-svelte/src/lib/components/MasonryGrid.svelte
<script>
	import { onMount } from 'svelte';
	import ArticleCard from './ArticleCard.svelte';
	import { articles, isLoading, hasMore, loadArticles } from '../stores/articles';

	export let onArticleClick;

	let sentinel;
	let observer;
	let columnCount = 4;
	let containerWidth = 0;

	// Distribute articles into columns
	$: columns = distributeIntoColumns($articles, columnCount);

	function distributeIntoColumns(items, numColumns) {
		const cols = Array.from({ length: numColumns }, () => []);
		items.forEach((item, index) => {
			cols[index % numColumns].push(item);
		});
		return cols;
	}

	function updateColumnCount() {
		if (typeof window !== 'undefined') {
			const width = window.innerWidth;
			if (width >= 1280) columnCount = 4;
			else if (width >= 1024) columnCount = 3;
			else if (width >= 640) columnCount = 2;
			else columnCount = 1;
		}
	}

	onMount(() => {
		updateColumnCount();

		const resizeObserver = new ResizeObserver(() => {
			updateColumnCount();
		});

		if (typeof window !== 'undefined') {
			resizeObserver.observe(document.body);
		}

		// Set up intersection observer for infinite scroll
		observer = new IntersectionObserver(
			(entries) => {
				if (entries[0].isIntersecting && $hasMore && !$isLoading) {
					loadArticles(false);
				}
			},
			{ threshold: 0.1 }
		);

		if (sentinel) {
			observer.observe(sentinel);
		}

		return () => {
			if (observer) observer.disconnect();
			resizeObserver.disconnect();
		};
	});
</script>

<div class="container mx-auto px-4 py-6">
	{#if $articles.length === 0 && !$isLoading}
		<div class="text-center py-12 text-gray-500">
			No articles yet. Add some feeds to get started!
		</div>
	{:else}
		<div class="masonry-grid" style="--column-count: {columnCount}">
			{#each columns as column, i (i)}
				<div class="masonry-column">
					{#each column as article (article.id)}
						<div class="masonry-item">
							<ArticleCard {article} on:click={() => onArticleClick(article)} />
						</div>
					{/each}
				</div>
			{/each}
		</div>
	{/if}

	{#if $isLoading}
		<div class="text-center py-8">
			<div class="inline-block animate-pulse text-gray-500">Loading...</div>
		</div>
	{/if}

	<!-- Sentinel for infinite scroll -->
	<div bind:this={sentinel} class="h-4"></div>
</div>

<style>
	.masonry-grid {
		display: grid;
		grid-template-columns: repeat(var(--column-count), 1fr);
		gap: 1rem;
	}

	.masonry-column {
		display: flex;
		flex-direction: column;
		gap: 1rem;
	}

	.masonry-item {
		break-inside: avoid;
	}
</style>
